services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: Example12345
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local